services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - d4g-internal
    ports:
      - '5432'

  init:
    restart: "no"
    build:
      context: .
      dockerfile: infra/ingestion/Dockerfile
    container_name: biolit-init
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgresql://biolit:biolit@postgres:5432/biolit
      POLARS_SKIP_CPU_CHECK: "1"
    command: ["sh", "-c", "uv run infra/ingestion/run.py && sleep 3600"]
    networks:
      - d4g-internal


  label-studio:
    image: heartexlabs/label-studio:1.13.1
    depends_on:
      - postgres
    environment:
      LABEL_STUDIO_BASE_DATA_DIR: /label-studio/data
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_HOST: https://biolit-labelstudio.services.d4g.fr
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - labelstudio_data:/label-studio/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.biolit-labelstudio.rule=Host(`biolit-labelstudio.services.d4g.fr`)
      - traefik.http.routers.biolit-labelstudio.entryPoints=webtls
      - traefik.http.routers.biolit-labelstudio.tls=true
      - traefik.docker.network=d4g-internal
      - traefik.http.services.biolit-labelstudio.loadbalancer.server.port=8080
    networks:
      - d4g-internal



volumes:
  postgres_data:
  labelstudio_data:

networks:
  d4g-internal:
    external: true